### ISSUE TITLE
Update the license to be Apache 2.0

### ISSUE THREAD

**Issue by joeddavis** [adron-orange/react-component-grid#12]
The license needs to be "Apache 2.0" according to THD OSS rules.

**Comment by joeddavis** [comment]
I can see that you have the LICENSE file correct.  Just need to update the package.json "license" property to reflect that.

**Comment by adron-orange** [comment]
oh... thought we had it set to that. Will update ASAP.

**Comment by adron-orange** [comment]
All set @joeddavis!  👍
