### ISSUE TITLE
lib/grid/gridBody.js uses British English spelling of initialise

### ISSUE THREAD

**Issue by joeddavis** [adron-orange/react-component-grid#13]
call me petty...

**Comment by adron-orange** [comment]
:P

**Comment by joeddavis** [comment]
gridColumn.js and gridRow.js use the same messaging.... on the same functions...

Is there a common location where those functions can be defined and shared rather than redefining them in each script?

**Comment by adron-orange** [comment]
Just kidding about the *wontfix* label.  :)   I'll let @jonnyohjonnyo take a hack at that.

**Comment by adron-orange** [comment]
Done.
