### ISSUE TITLE
Get a working build, add build badge (Tracis-CI)

### ISSUE THREAD

**Issue by adron-orange** [adron-orange/react-component-grid#3]

**Comment by adron-orange** [comment]
I can handle getting this rolled in to, but might be better if you tackle it @jonnyohjonnyo.

**Comment by jonnyohjonnyo** [comment]
@adron-orange can you please make me an admin on this repo? it looks like Travis requires that before I can add the repo to my Travis account

_The ones you have administrative access to are the ones you can enable the service hook for._

**Comment by adron-orange** [comment]
@jonnyohjonnyo I've got you setup as a collaborator, which I believed was admin access. There isn't a setting that I can set you to that makes you owner or admin, but I'm looking for it.

**Comment by adron-orange** [comment]
@jonnyohjonnyo implemented. Done deal.
